
services:
  db:
    image: mysql:8.0
    container_name: "${DB_HOST}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: Asia/Seoul
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 5s
      timeout: 30s
      retries: 100
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/x86_64
    networks:
      - django-redis-project

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - django-redis-project

  web:
    build: .
    working_dir: /app
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysql:3306 -s -t 30
        python manage.py migrate && python manage.py migrate
        python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${MYSQL_DATABASE}"
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      REDIS_HOST: "${REDIS_HOST}"
    networks:
      - django-redis-project

volumes:
  db_data:


networks:
  django-redis-project:
    driver: bridge